# Generated by Django 5.2.7 on 2026-01-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_song_source_label_remove_song_source_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='React',
        ),
    ]
